platform :ios, '9.0'
use_frameworks!

target 'RGInnerBadgeButton_Example' do
    pod 'RGInnerBadgeButton', :path => '../'

    target 'RGInnerBadgeButton_Tests' do
        inherit! :search_paths

        pod 'Quick'
        pod 'Nimble'
        pod 'FBSnapshotTestCase'
        pod 'Nimble-Snapshots'
    end
end
